### ISSUE TITLE
Typo3 v12

### ISSUE THREAD

**Issue by plojewski** [nitsan-technologies/ns_gridtocontainer#3]
Hi there, are you planning support for version 12 of Typo3?

**Comment by nitsan-technologies** [comment]
Hey @plojewski 

Nice to e-meet you! Thanks for reaching out and your interest in our TYPO3 extension. Yes, we have planned to support TYPO3 v12. You can expect it in the upcoming weeks.

Cheers!

**Comment by plojewski** [comment]
Thank you! :)

**Comment by ma-gu-16** [comment]
are there any beta versions ?

**Comment by nitsan-technologies** [comment]
Hello guys,

Thank you for your interest in our extension. We're excited to announce that it is now compatible with TYPO3 v12.

You can find the latest release here: [TAG 2.0.0](https://github.com/nitsan-technologies/ns_gridtocontainer/releases/tag/2.0.0).

Thanks!

Team @nitsan-technologies :)
