### ISSUE TITLE
No flexform migration

### ISSUE THREAD

**Issue by Oktopuce** [nitsan-technologies/ns_gridtocontainer#4]
As far as I see in code, there is no Flexform migration while here it's written here https://t3planet.com/typo3-gridelements-container this: 

> Support Flexform
> 
> The migration module will take care of creating and migrating all Flexform settings of your existing Gridelements to the container. You don’t need to follow unnecessary steps.
> 

And nothing is documented about that in extension documentation.

The question is : is it possible with the current version to also migrate Flexform ?

**Comment by nitsan-technologies** [comment]
Hey @Oktopuce,

The FlexForm configuration is being migrated with the extension. We're updating the grid element to a container, and the FlexForm settings will be automatically converted from grid to container. Your grid FlexForm settings will be adjusted to the new container setup. For now, we are closing this issue.

If you have any questions, feel free to contact us.

Thanks,
Team @nitsan-technologies
